### PR TITLE
Target: Create jar, Version control for all build scripts

### LINKED ISSUE #9: Target: Create jar
add a gradle target to create the dungeon.jar

### LINKED ISSUE #69: Version control for all build scripts
For didactic reason, this project should contain ANT, Maven and Gradle as build scripts.
Is there a chance to somehow define and maintain the version numbers in a common file?

### PR DESCRIPTION
**Pull request by Tobias321**
resolves #9 , resolves #69 

Run: `gradlew jar` -> `build/libs/pmdungeon-1.0.jar`
or
run: `ant jar` -> `build/jar/pmdungeon.jar`
or
run: `mvn clean compile assembly:single` -> `target/pmdungeon-1.0-jar-with-dependencies.jar`

Properties for Gradle and Ant are in the `build.properties` file.
Properties for Maven/`pom.xml` aren't possible. 🙁 

Btw. i fixed some Gradle dependencies...

### CODE REVIEW

**Comment by Tobias321** [comment]
can someone please approve? works on windows and linux/ubuntu. i can't test this on macos.

**Comment by AMatutat** [comment]
will have a look at this later (windows). 

Do we care about MacOS?

**Comment by Tobias321** [comment]
thanks.

> Do we care about MacOS?

not from my side. 🙊

**Comment by cagix** [comment]
> thanks.
> 
> > Do we care about MacOS?
> 
> not from my side. 🙊

oi! assign this to @RipDip for review ...

**Review by AMatutat — CHANGES_REQUESTED** [review]
All three works just fine on Windows.

Question: Is there any reason why we have three different output folders and names for the jar?
Couldn't we just say its always `builds/jar/pmdungeon.jar`?

Also, I prefer we do not use version numbers. 
It's just a pain to keep this consistent.

**Comment by Tobias321** [comment]
fine. 🙂 jars can be found here now: `target/pmdungeon.jar`.

**Review by AMatutat — APPROVED** [review]

**Comment by RipDip** [comment]
I can create the jar with gradle and maven under MAC OS, but with ANT I only get errors. I have to see if I can fix it.

If I build the dungeon with Gradle it works, but it doesn't work with Maven and Ant yet.

**Review by RipDip — APPROVED** [review]

**Pull request merged**
