### PR TITLE
Fix firstFrame get called twice #31

### LINKED ISSUE #31: firstFrame get called twice
- gdx.graphics.setWindowedMode() calls render() and this will call firstFrame() again.

### PR DESCRIPTION
**Pull request by Tobias321**
fixes #31

### CODE REVIEW

**Comment by cagix** [comment]
@Tobias321 Does that mean, #40 is working in the end?

**Comment by Tobias321** [comment]
> @Tobias321 Does that mean, #48 is working in the end?

@cagix #48 is working propertly from my point of view.

**Comment by AMatutat** [comment]
looks good to me.

**Comment by Alizame** [comment]
Hi, 
is the indentation change from spaces to tabs on purpose?

**Comment by Tobias321** [comment]
> Hi,
> is the indentation change from spaces to tabs on purpose?

No, please see 46680ca

**Comment by cagix** [comment]
> is the indentation change from spaces to tabs on purpose?

good catch 👍

**Review by AMatutat — CHANGES_REQUESTED** [review]
Can you use #54 for Code style?

**Comment by Tobias321** [comment]
> Can you use #54 for Code style?

Yes, give me a few minutes

**Pull request merged**
