### PR TITLE
Build-System: Port to Maven

### LINKED ISSUE #41: add Maven
add Maven as second build tool 

#38 #39

### PR DESCRIPTION
**Pull request by Alizame**
I have successfully ported the project to Maven.

I tested it on my machine with the sample project that @AMatutat sent me, where it works, 
and I also sent it to a friend of mine that actually uses this lib for PM, who confirmed that it works for him too.

To build the jar file just do `mvn package`.
The finished jar-file is in the `/target` folder.

(I didn't port the gradle tasks ***run*** and ***debug***, as this is a library -> it doesn't have an entry point)

Looking for feedback @AMatutat .
I could add a maven-goal to create the ***javadoc*** ?

---

fixes #41, in conflict w/ #39

### CODE REVIEW

**Comment by cagix** [comment]
like the idea 👍

**Comment by cagix** [comment]
could we keep the gradle configuration for educational purposes, please?

**Comment by Alizame** [comment]
@cagix Sure thing, done!

**Comment by Zitrustee** [comment]
Is it alright if we also use this port in our project?

**Comment by cagix** [comment]
> Is it alright if we also use this port in our project?

shire, why not?

**Comment by CrappyAlgorithm** [comment]
I have just compared your solution with mine in #39 and think your variant is better, because with yours the pmdungeon.jar is in the root project.

But I have two adjustments:
- I am not quite sure about your variant, but the assembly plugin does not have to be used for the sub project core.
- It might be nice to define the versions in a properties block as variables. This is especially worthwhile if you want to adjust the libGDX version at some point.

**Comment by cagix** [comment]
> * I am not quite sure about your variant, but the assembly plugin does not have to be used for the sub project core.

not sure about that, either.

> * It might be nice to define the versions in a properties block as variables. This is especially worthwhile if you want to adjust the libGDX version at some point.

definitively! good point.

> * de.fhbielefeld should fit better as groupId than pmdungeon

i tend to agree, but we are only a small project and technically do not represent FHB. i am not sure if we are officially (legally) allowed to hijack the namespace :)

**Comment by Alizame** [comment]
> I am not quite sure about your variant, but the assembly plugin does not have to be used for the sub project core.

You are correct, I'll fix that!

> It might be nice to define the versions in a properties block as variables. This is especially worthwhile if you want to adjust the libGDX version at some point.

I could do that, sure.

> de.fhbielefeld should fit better as groupId than pmdungeon

>i tend to agree, but we are only a small project and technically do not represent FHB. i am not sure if we are officially (legally) allowed to hijack the namespace :)

Does someone have a good idea for a namespace?

de.notfhbielefeld mabye? ; )

**Comment by cagix** [comment]
> > > de.fhbielefeld should fit better as groupId than pmdungeon
> 
> > i tend to agree, but we are only a small project and technically do not represent FHB. i am not sure if we are officially (legally) allowed to hijack the namespace :)
> 
> Does someone have a good idea for a namespace?
> 
> de.notfhbielefeld mabye? ; )

what about `de.pmdungeon`? plain, simple, free ...

**Comment by CrappyAlgorithm** [comment]
> Does someone have a good idea for a namespace?
  de.notfhbielefeld mabye? ; )

Maybe simply adding a subgroup _de.fhbielefeld.programmiermethoden_ 
But i'm not sure if this is allowed.

Or _com.github.amatutat_ to stay in naming convention

**Comment by cagix** [comment]
> > Does someone have a good idea for a namespace?
> > de.notfhbielefeld mabye? ; )
> 
> Maybe simply adding a subgroup _de.fhbielefeld.programmiermethoden_
> But i'm not sure if this is allowed.
> 
> Or _com.github.amatutat_ to stay in naming convention

i'd refrain from all references to the fhb, if you ask me :)

Involving @AMatutat  seems like a sensible idea to me, as long as he continues to maintain and develop the library in the years to come.

**Review by Tobias321 — COMMENTED** [review]
Output from `mvn clean package -U`:
```
[ERROR] Failed to execute goal on project desktop: Could not resolve dependencies for project de.pmdungeon:desktop:jar:1.0: Could not find artifact pmdungeon:core:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by Alizame** [comment]
> Output from `mvn clean package -U`:
> 
> ```
> [ERROR] Failed to execute goal on project desktop: Could not resolve dependencies for project de.pmdungeon:desktop:jar:1.0: Could not find artifact pmdungeon:core:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
> ```

Weird, I can not replicate this behavior on my machine.
It seems like it doesn't resolve the dependency via the local maven repository.
Maybe your maven version is outdated? I have the latest version and it works.

> C:\Users\maxif\IntellijProjects\pmdungeon_fork>mvn --version
> Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
> Maven home: C:\Maven\apache-maven-3.8.1\bin\..
> Java version: 11.0.8, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.8
> Default locale: de_DE, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Alizame** [comment]
Oh, I think I fixed it. 
Can you try it again @Tobias321 ?

**Comment by Tobias321** [comment]
> Oh, I think I fixed it.
> Can you try it again @Tobias321 ?

Thanks, build success now.

**Comment by AMatutat** [comment]
#38 and #39 will be combined 

#39 is already merged into the maven branch so we have to fix the conflicts in this PR and cherry pick. 
This is #41

**Comment by Kushurando** [comment]
Changed the groupID as requested, and added dependency management to resolve the conflict, should work just fine now.

**Pull request merged**
