### PR TITLE
Upgrade Gradle

### PR DESCRIPTION
**Pull request by cagix**
this is an feable attempt to upgrade gradle version to 7.0.2

* step 1: update gradlew to 7.0.2 (7f45c37)
* step 2: update gradle config
    * clean manual gradle configuration following gradle documentation failed due to several libgdx-setup issues (1e22dd8)
    * using libgdx-builder (https://libgdx.com/dev/project-generation/) produces a mess of a gradle config, but at least it seems to be working (again)  (4b738ed)

`sh ./gradlew clean core:compileJava desktop:compileJava --info` seems to be working now.

@AMatutat **Please check carefully using a dummy implementation before even thinking of merging!**

---

fixes #47

### CODE REVIEW

**Review by Tobias321 — APPROVED** [review]
works as intended

**Comment by Tobias321** [comment]
I can import it into eclipse, but to run the game (resp. to use the projects) i've to reference (/point to) the projects and to manually add the gdx jar to the class path; also Java 11 is used for the projects. Is that all intended? If so, then LGTM. :)

**Comment by cagix** [comment]
> I can import it into eclipse, but to run the game (resp. to use the projects) i've to reference (/point to) the projects 

hmmm, that could be the behaviour of the original configuration as well?

> and to manually add the gdx jar to the class path; 

ouch. then we are missing some dependencies. the libgdx-setup-builder moved some dependencies from "implementation" to "api", maybe this is not the intended behaviour ... 

> also Java 11 is used for the projects. Is that all intended? If so, then LGTM. :)

should work also with java 16, but the students are working with the current lts version, i.e. java 11.

**Comment by AMatutat** [comment]
- if building a `jar` out of this (like i did with the original) I have no access to the external libs (gdx, gjson ...)
- While trying to implement an example in this project (no jar) I have several access issues.

**Comment by AMatutat** [comment]
seems to work now

**Comment by Tobias321** [comment]
> seems to work now
> 
> @Tobias321 can you check it again? (build an run)
> 
> edit: @Tobias321 the `assets` folder needs to be in `./desktop/` ... please clean your gradle cache, i.e. remove `~/.gradle/` and `<project>/.gradle/` before running `./gradlew desktop:run`

@AMatutat 

I had to add a main method in DesktopLauncher.java (aside the run method), then i can do problem-free two things:

1. `gradlew build` to build it
2. `gradlew run` (or even `gradlew desktop:run`) to run the game

Eclipse integration:

3. I can import it into Eclipse via Import Existing Gradle Project,
4. but if I try to run the `DesktopLauncher` class, following output:

```
Error: Could not find or load main class de.fhbielefeld.pmdungeon.desktop.DesktopLauncher
Caused by: java.lang.ClassNotFoundException: de.fhbielefeld.pmdungeon.desktop.DesktopLauncher
```

Not sure, if that is relevant.

If I point to `pmdungeon-core` and `pmdungeon-desktop` from another project in Eclipse, I have to add the gdx jar file to the build path to have a proper setup. But I'm also not sure, if that is relevant.

So it seems to work (at least the first part).

**Comment by cagix** [comment]
@Tobias321 @AMatutat Hmmm, looks like Gradle works per se now. Thats good news :)  To properly support Eclipse, we'd need to add some Eclipse specific lines to the Gradle config ... @Tobias321 Could you check the Gradle documentation, what we can do here?

**Comment by Tobias321** [comment]
> Could you check the Gradle documentation, what we can do here?

@cagix I think, I must install IntelliJ first for that 😬 

seems, ij has a plugin for exporting a project to Eclipse: `https://www.jetbrains.com/help/idea/exporting-an-intellij-idea-project-to-eclipse.html` you could test that and compare the outputs...

I'll try it. 🙂

**Comment by cagix** [comment]
> @cagix I think, I must install IntelliJ first for that 😬

hmmmm, i think, gradle itself provides some sort of plugin to support Eclipse (better/at all). no need to user intellij :)

**Comment by Tobias321** [comment]
> no need to use intellij :)

👍 

I found out that you can click on `Gradle Tasks | three dots | Show All Tasks` in Eclipse. Than you can start the application by clinking `pmdungeon > other > run`. But I don't know, what we have to modify in the `build.gradle` files, in order to Eclipse recognize that by itself, sorry. 🙁

**Comment by cagix** [comment]
@Tobias321 I had a quick search on your behalf. Please check this out: https://docs.gradle.org/current/userguide/eclipse_plugin.html

**Comment by Tobias321** [comment]
🙈 

@cagix You can simply call `gradlew eclipse`, the project files for eclipse will be generated, and than you can "simply" click on "Import... > General > Existing Projects into Workspace", check the "Search for nested projects" option, and select the three projects. After that Eclipse has the Gradle Tasks. I think, the current gradle configurations files are ok.

**Comment by cagix** [comment]
so, you can confirm it's working now, even in eclipse?

**Comment by cagix** [comment]
@Tobias321 do we need to add the `apply eclipse` lines to `biuld.gradle`?

**Comment by Tobias321** [comment]
> so, you can confirm it's working now, even in eclipse?

yes

> do we need to add the `apply plug-in: 'eclipse'` lines to `build.gradle`?

also yes, we need the `apply plug-in: 'eclipse'` line in `allprojects { ...` etc., otherwise gradlew don't know that target/task.

**Comment by cagix** [comment]
@Tobias321 thx :)   i've added the `apply plug-in: 'eclipse'` lines to `build.gradle` ...

@RipDip @timonBusch could you please give this a quick review, too? thx.

**Comment by cagix** [comment]
@timonBusch you approved this PR and afterwards self-requested a review? sure about that? ;)

Screenshot 2021-06-14 at 16 28 11

**Comment by Tobias321** [comment]
@cagix I can't build the jar with all dependencies any more with task `jar` or `desktop:jar`. :(

**Comment by cagix** [comment]
@Tobias321 could please create a new issue (and link to this one)? 

we could reopen this issue, but there is quit some "noise" here, so maybe it's better to just use a clean ticket :)

**Comment by Tobias321** [comment]
@cagix i think, this issue go with pr #65 ...

perhaps, no need for creating a new issue :)

**Pull request merged**
