### PR TITLE
Fixed: maven build script

### PR DESCRIPTION
**Pull request by CrappyAlgorithm**
The maven build script was not longer creating the independent jar.

I removed the pluginManagement tag from build, since this is used to configurate plugins for sub modules. Now the independent jar will be created like intended.

### CODE REVIEW

**Comment by Tobias321** [comment]
The jar with dependencies are built with `mvn clean compile assembly:single`. I think, we can close this pr.

**Comment by CrappyAlgorithm** [comment]
Yes ok that depends on what you want. Without pluginManagement maven builds the jar also at `mvn package`. 

And generally the pluginManagement is to set the plugins configuration in the parent pom for all sub modules. Since there are no modules anymore it is actually unnecessary.

**Comment by cagix** [comment]
and `mvn package` is easier to remember than the current command ...

**Comment by CrappyAlgorithm** [comment]
https://maven.apache.org/pom.html#plugin-management

I also understand that the settings do not apply to the project, but only to the sub modules. This would also explain why only the direct target works. This would probably cause problems with plugins like jacoco.

**Review by Tobias321 — APPROVED** [review]
Ok, i didn't have see/recognize this. I think, we can merge. lgtm

**Comment by AMatutat** [comment]
LGTM

**Pull request merged**
